###################################################
# Appium
###################################################

appium.url=http://127.0.0.1:4723

###################################################
# Android
###################################################

platform.name=Android
automation.name=UiAutomator2
device.name=Android

###################################################
# APK
###################################################

app.path=apps/app-debug.apk

###################################################
# Timeout
###################################################

implicit.wait=10
explicit.wait=20